"""IH2662 Week 3: reproducible Gmsh / DEVSIM silicon baseline.
Units in the solver and mesh: cm, V, cm^-3. Plot positions: micrometres.
Uses installed DEVSIM simple_physics helpers (Apache-2.0, DEVSIM LLC).
"""
from pathlib import Path
import argparse, csv, json, math, os, sys, time
ROOT = Path(__file__).resolve().parent
PROJECT = ROOT.parent
sys.path.insert(0, str(PROJECT / "examples" / "diode"))
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.tri as mtri

def settings():
    return json.loads((ROOT / "parameters.json").read_text(encoding="utf-8-sig"))

def geometry(p, planar=False, scale=1):
    u = 1e-4
    w = (p["planar_control_width_um"] if planar else p["device_width_um"])*u
    d = (p["drift_thickness_um"]+p["junction_depth_um"])*u
    j = p["junction_depth_um"]*u
    a = p["implant_flat_extent_um"]*u
    c = p["anode_extent_um"]*u
    h = p["mesh_junction_um"]*u*scale
    b = p["mesh_bulk_um"]*u*scale
    if planar:
        body = f"""
Point(1)={{0,0,0,{h}}}; Point(2)={{{w},0,0,{h}}};
Point(3)={{{w},{d},0,{b}}}; Point(4)={{0,{d},0,{b}}};
Point(10)={{0,{j},0,{h}}}; Point(11)={{{w},{j},0,{h}}};
Line(1)={{1,2}}; Line(2)={{2,11}}; Line(3)={{3,4}}; Line(4)={{4,10}};
Line(5)={{11,3}}; Line(6)={{10,1}};
Curve Loop(1)={{1,2,5,3,4,6}}; Plane Surface(1)={{1}};
Line(10)={{10,11}}; Curve{{10}} In Surface{{1}};
Physical Curve("anode")={{1}};
Physical Curve("cathode")={{3}};
"""
    else:
        body = f"""
Point(1)={{0,0,0,{h}}}; Point(2)={{{c},0,0,{h}}};
Point(3)={{{a+j},0,0,{h}}}; Point(4)={{{w},0,0,{b}}};
Point(5)={{{w},{d},0,{b}}}; Point(6)={{0,{d},0,{b}}};
Point(10)={{0,{j},0,{h}}}; Point(11)={{{a},{j},0,{h}}};
Line(1)={{1,2}}; Line(2)={{2,3}}; Line(3)={{3,4}};
Line(4)={{4,5}}; Line(5)={{5,6}}; Line(6)={{6,10}}; Line(7)={{10,1}};
Curve Loop(1)={{1,2,3,4,5,6,7}}; Plane Surface(1)={{1}};
Point(12)={{{a},0,0,{h}}};
Line(10)={{10,11}}; Circle(11)={{11,12,3}};
Curve{{10,11}} In Surface{{1}};
Physical Curve("anode")={{1}};
Physical Curve("cathode")={{5}};
"""
    curves = "10" if planar else "10,11"
    return f"""// Generated by silicon_baseline.py from parameters.json.
// Coordinates are cm. y increases DOWN into the silicon.
// Embedded curves mark NetDoping=0; all silicon is a single region.
{body}
Physical Surface("Silicon")={{1}};
Field[1]=Distance; Field[1].CurvesList={{{curves}}}; Field[1].Sampling=500;
Field[2]=Threshold; Field[2].InField=1;
Field[2].SizeMin={h}; Field[2].SizeMax={b};
Field[2].DistMin={0.7*u}; Field[2].DistMax={10*u};
Background Field=2;
Mesh.MeshSizeMin={h}; Mesh.MeshSizeMax={b};
Mesh.Algorithm=5;
Mesh.MshFileVersion=2.2;
Mesh.Binary=0;
"""

def mesh(p, out, planar, scale):
    import gmsh
    geo = out/"silicon_junction.geo"
    geo.write_text(geometry(p, planar, scale), encoding="utf-8")
    gmsh.initialize()
    try:
        gmsh.open(str(geo))
        gmsh.model.mesh.generate(2)
        if not len(gmsh.model.mesh.getElements(2)[1][0]): raise RuntimeError("Gmsh produced no triangles")
        gmsh.write(str(out/"silicon_junction.msh"))
    finally:
        gmsh.finalize()
    print("PASS: Gmsh mesh created.", flush=True)

def plot_mesh(x, y, triangles, doping, out):
    triang=mtri.Triangulation(x*1e4,y*1e4,triangles)
    fig, ax=plt.subplots(figsize=(9,5))
    ax.triplot(triang,linewidth=.2,color="0.5")
    ax.tricontour(triang,doping,levels=[0],colors=["red"],linewidths=1.2)
    ax.set(xlabel="x (um)",ylabel="Depth (um)",title="Silicon mesh; red = p-n junction")
    ax.invert_yaxis(); ax.set_aspect("equal")
    fig.tight_layout(); fig.savefig(out/"mesh.png",dpi=180); plt.close(fig)

def build(p,out,planar):
    import devsim as ds
    for option in ["extended_solver","extended_model","extended_equation"]:
        ds.set_parameter(name=option,value=p.get("_precision","double")=="extended")
    import devsim.umfpack.umfshim  # bundled alternate sparse solver
    import diode_common as dc
    from devsim.python_packages.simple_physics import GetContactBiasName
    D,R="silicon_week3","Silicon"
    args=dict(device=D,region=R)
    ds.create_gmsh_mesh(mesh="week3",file=str(out/"silicon_junction.msh"))
    ds.add_gmsh_region(mesh="week3",gmsh_name="Silicon",region=R,material="Silicon")
    for c in ["anode","cathode"]:
        ds.add_gmsh_contact(mesh="week3",gmsh_name=c,region=R,name=c,material="metal")
    ds.finalize_mesh(mesh="week3"); ds.create_device(mesh="week3",device=D)
    dc.SetParameters(D,R)
    q=1.602176634e-19
    k=1.380649e-23
    params={"Permittivity":p["relative_permittivity"]*8.8541878128e-14,
            "ElectronCharge":q,"T":p["temperature_K"],"kT":k*p["temperature_K"],
            "V_t":k*p["temperature_K"]/q,"mu_n":p["electron_mobility_cm2_Vs"],
            "mu_p":p["hole_mobility_cm2_Vs"],"n_i":p["intrinsic_cm3"],
            "n1":p["intrinsic_cm3"],"p1":p["intrinsic_cm3"],
            "taun":p["lifetime_s"],"taup":p["lifetime_s"]}
    for name,value in params.items(): ds.set_parameter(**args,name=name,value=value)
    # Gaussian acceptor diffusion. NetDoping=0 exactly on depth/radius j.
    length=p["junction_depth_um"]*1e-4/math.sqrt(math.log(p["acceptor_peak_cm3"]/p["donor_cm3"]))
    lateral="0" if planar else f"max(x-{p['implant_flat_extent_um']*1e-4},0)^2"
    ds.node_model(**args,name="Donors",equation=format(p["donor_cm3"],".17e"))
    ds.node_model(**args,name="Acceptors",equation=f"{p['acceptor_peak_cm3']:.17e}*exp(-(y^2+{lateral})/{length**2})")
    ds.node_model(**args,name="NetDoping",equation="Donors-Acceptors")
    x=np.array(ds.get_node_model_values(**args,name="x"))
    y=np.array(ds.get_node_model_values(**args,name="y"))
    triangles=np.array(ds.get_element_node_list(**args),dtype=int)
    nd=np.array(ds.get_node_model_values(**args,name="NetDoping"))
    lateral_distance = np.zeros_like(x) if planar else np.maximum(x-p["implant_flat_extent_um"]*1e-4,0)
    expected_doping = p["donor_cm3"]-p["acceptor_peak_cm3"]*np.exp(-(y*y+lateral_distance*lateral_distance)/(length*length))
    if not np.allclose(nd,expected_doping,rtol=1e-10,atol=1e3):
        raise RuntimeError("Doping expression does not match the specified profile")
    if nd.min()>=0 or nd.max()<=0: raise RuntimeError("Both p and n regions are required")
    print(f"CHECK: NetDoping range {nd.min():.4e} to {nd.max():.4e} cm^-3",flush=True)
    if triangles.ndim!=2 or triangles.shape[1]!=3: raise RuntimeError("Expected linear triangles")
    plot_mesh(x,y,triangles,nd,out)
    dc.InitialSolution(D,R)
    # Charge-neutral initial potential considerably improves initial convergence.
    ds.set_node_values(**args,name="Potential",values=(params["V_t"]*np.arcsinh(nd/(2*p["intrinsic_cm3"]))).tolist())
    ds.solve(type="dc",symbolic_iteration_limit=0,absolute_error=1,relative_error=1e-10,maximum_iterations=100)
    dc.DriftDiffusionInitialSolution(D,R)
    ds.solve(type="dc",symbolic_iteration_limit=0,absolute_error=(1e-2 if p.get("_precision")=="extended" else 1e4),relative_error=(1e-9 if p.get("_precision")=="extended" else 1e-4),maximum_iterations=100)
    return ds,D,R,x,y,triangles,nd

def field(potential,x,y,tri):
    # Exact -gradient of piecewise-linear potential on each triangle.
    tx=x[tri]; ty=y[tri]; v=potential[tri]
    dx1=tx[:,1]-tx[:,0]; dx2=tx[:,2]-tx[:,0]
    dy1=ty[:,1]-ty[:,0]; dy2=ty[:,2]-ty[:,0]
    det=dx1*dy2-dx2*dy1
    if np.any(abs(det)<1e-30): raise RuntimeError("Degenerate triangle")
    ex=-((v[:,1]-v[:,0])*dy2-(v[:,2]-v[:,0])*dy1)/det
    ey=-(dx1*(v[:,2]-v[:,0])-dx2*(v[:,1]-v[:,0]))/det
    return ex,ey,np.hypot(ex,ey)

def export(ds,D,R,x,y,tri,nd,out,label,bias):
    import pyvista as pv
    args=dict(device=D,region=R)
    pot=np.array(ds.get_node_model_values(**args,name="Potential"))
    ex,ey,mag=field(pot,x,y,tri)
    grid=pv.UnstructuredGrid(np.column_stack((np.full(len(tri),3),tri)).ravel(),
                             np.full(len(tri),5,dtype=np.uint8),
                             np.column_stack((x*1e4,y*1e4,np.zeros(len(x)))))
    grid.point_data["Potential_V"]=pot
    grid.point_data["NetDoping_cm-3"]=nd
    for name in ["Electrons","Holes"]:
        grid.point_data[name+"_cm-3"]=ds.get_node_model_values(**args,name=name)
    grid.cell_data["ElectricField_V_cm"]=mag
    grid.cell_data["ElectricFieldVector_V_cm"]=np.column_stack((ex,ey,np.zeros(len(ex))))
    grid.field_data["ReverseVoltage_V"]=np.array([bias])
    grid.save(str(out/(label+".vtu")))
    triang=mtri.Triangulation(x*1e4,y*1e4,tri)
    fig,ax=plt.subplots(figsize=(9,5))
    im=ax.tripcolor(triang,facecolors=mag/1e5,shading="flat",cmap="inferno")
    ax.tricontour(triang,nd,levels=[0],colors=["cyan"],linewidths=.8)
    i=int(np.argmax(mag))
    ax.plot(x[tri[i]].mean()*1e4,y[tri[i]].mean()*1e4,"x",color="lime",label="Peak field")
    ax.set(xlabel="x (um)",ylabel="Depth (um)",title=f"Silicon: reverse voltage {bias:g} V")
    ax.invert_yaxis(); ax.set_aspect("equal"); ax.legend(loc="upper right")
    fig.colorbar(im,ax=ax,label="Electric field (100,000 V/cm)")
    fig.tight_layout(); fig.savefig(out/(label+"_field.png"),dpi=180); plt.close(fig)

def simulate(p,out,planar,equilibrium):
    ds,D,R,x,y,tri,nd=build(p,out,planar)
    from devsim.python_packages.simple_physics import GetContactBiasName
    args=dict(device=D,region=R)
    export(ds,D,R,x,y,tri,nd,out,"equilibrium",0)
    if equilibrium:
        print("PASS: zero-bias drift-diffusion solution and plots saved.",flush=True)
        return
    rows=[]
    def sample(v):
        pot=np.array(ds.get_node_model_values(**args,name="Potential"))
        _,_,mag=field(pot,x,y,tri)
        if not np.all(np.isfinite(mag)): raise RuntimeError("Non-finite electric field")
        i=int(np.argmax(mag))
        currents=[]
        for c in ["anode","cathode"]:
            currents.append(sum(ds.get_contact_current(device=D,contact=c,equation=e) for e in
                                ["ElectronContinuityEquation","HoleContinuityEquation"]))
        row=[v,float(mag[i]),float(x[tri[i]].mean()*1e4),float(y[tri[i]].mean()*1e4),*currents]
        rows.append(row)
        with (out/"peak_field.csv").open("w",newline="") as f:
            writer=csv.writer(f); writer.writerow(["reverse_voltage_V","peak_field_V_cm","peak_x_um","peak_depth_um","anode_A_per_cm","cathode_A_per_cm"]); writer.writerows(rows)
        print(f"BIAS {v:8.3f} V | peak {mag[i]:.6g} V/cm | x={row[2]:.3f}, depth={row[3]:.3f} um",flush=True)
    sample(0)
    v=0.
    crossing=None
    step=0.1
    previous_state=None
    previous_voltage=None
    while v<p["max_voltage_V"] and rows[-1][1]<p["critical_field_V_cm"]:
        if rows[-1][1] > .90*p["critical_field_V_cm"]: step=min(step,p["crossing_step_V"])
        dv=min(step,p["max_voltage_V"]-v)
        saved={n:list(ds.get_node_model_values(**args,name=n)) for n in ["Potential","Electrons","Holes"]}
        while True:
            trial=v+dv
            if previous_state is not None:
                ratio=dv/(v-previous_voltage)
                for name in saved:
                    current=np.asarray(saved[name])
                    previous=np.asarray(previous_state[name])
                    if name=="Potential":
                        predicted=current+ratio*(current-previous)
                    else:
                        change=np.log(np.maximum(current,1e-300))-np.log(np.maximum(previous,1e-300))
                        predicted=current*np.exp(np.clip(ratio*change,-3,3))
                    ds.set_node_values(**args,name=name,values=predicted.tolist())
            ds.set_parameter(device=D,name=GetContactBiasName("anode"),value=-trial)
            try:
                ds.solve(type="dc",symbolic_iteration_limit=0,absolute_error=(1e-2 if p.get("_precision")=="extended" else 1e4),relative_error=(1e-8 if p.get("_precision")=="extended" else 1e-4),maximum_iterations=40)
                break
            except ds.error:
                for n,values in saved.items(): ds.set_node_values(**args,name=n,values=values)
                ds.set_parameter(device=D,name=GetContactBiasName("anode"),value=-v)
                dv/=2
                if dv<.02: raise RuntimeError(f"Convergence failed near {trial:g} V; partial CSV retained.")
                print(f"Retry with {dv:g} V step",flush=True)
        previous_state=saved; previous_voltage=v
        v=trial; sample(v)
        step=min(p["voltage_step_V"],dv*1.5)
        if rows[-1][1]>=p["critical_field_V_cm"] and len(rows)>1:
            lo,hi=rows[-2],rows[-1]
            crossing=lo[0]+(p["critical_field_V_cm"]-lo[1])*(hi[0]-lo[0])/(hi[1]-lo[1])
    export(ds,D,R,x,y,tri,nd,out,"final",v)
    a=np.array(rows)
    fig,ax=plt.subplots(figsize=(8,5))
    ax.plot(a[:,0],a[:,1]/1e5,".-",label="2D drift-diffusion simulation")
    ax.axhline(p["critical_field_V_cm"]/1e5,color="red",ls="--",label="Hand-calculation critical field")
    eps=p["relative_permittivity"]*8.8541878128e-14
    q=1.602176634e-19
    ax.plot(a[:,0],np.sqrt(2*q*p["donor_cm3"]*a[:,0]/eps)/1e5,ls=":",label="Ideal abrupt 1D (built-in voltage omitted)")
    if crossing is not None: ax.axvline(crossing,color="green",ls="--",label=f"Field criterion: {crossing:.1f} V")
    ax.set(xlabel="Reverse-voltage magnitude (V)",ylabel="Peak electric field (100,000 V/cm)",title="Planar control" if planar else "Plain junction with a curved edge")
    ax.grid(alpha=.25); ax.legend(); fig.tight_layout(); fig.savefig(out/"peak_field.png",dpi=180); plt.close(fig)
    summary={"case":"planar_control" if planar else "edge_baseline","criterion_voltage_V":crossing,
             "last_voltage_V":v,"last_peak_field_V_cm":rows[-1][1],"nodes":len(x),"triangles":len(tri),
             "ideal_abrupt_voltage_from_constants_V":eps*p["critical_field_V_cm"]**2/(2*q*p["donor_cm3"]),
             "criterion":"constant peak-field threshold; no impact ionization model",
             "mesh_convergence":"Not established by one run. Compare with --mesh-scale 0.7.",
             "parameters":p}
    (out/"summary.json").write_text(json.dumps(summary,indent=2),encoding="utf-8")
    if crossing is None: raise RuntimeError("No critical-field crossing before max_voltage_V; see CSV.")
    print(f"PASS: field criterion reached at approximately {crossing:.2f} V. See peak_field.png.",flush=True)

def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action",choices=["mesh","equilibrium","run","view-mesh"])
    parser.add_argument("--planar",action="store_true",help="flat junction control, without curved edge")
    parser.add_argument("--mesh-scale",type=float,default=1,help="0.7 makes a finer mesh")
    parser.add_argument("--precision",choices=["double","extended"],default="double")
    opt=parser.parse_args()
    if opt.mesh_scale<=0: parser.error("--mesh-scale must be positive")
    p=settings(); p["_precision"]=opt.precision
    out=ROOT/"results"/(("planar" if opt.planar else "baseline")+f"_{opt.precision}_h{opt.mesh_scale:g}")
    out.mkdir(parents=True,exist_ok=True)
    (out/"parameters_used.json").write_text(json.dumps(p,indent=2),encoding="utf-8")
    if opt.action=="view-mesh":
        import gmsh
        if not (out/"silicon_junction.msh").exists(): mesh(p,out,opt.planar,opt.mesh_scale)
        gmsh.initialize()
        try:
            gmsh.open(str(out/"silicon_junction.msh"))
            gmsh.fltk.run()
        finally: gmsh.finalize()
        return
    mesh(p,out,opt.planar,opt.mesh_scale)
    if opt.action!="mesh": simulate(p,out,opt.planar,opt.action=="equilibrium")

if __name__=="__main__":
    main()
